'use strict';

angular.module('services')
.service('Data', function () {
    return {
        id: '0',
        name: 'Thing',
        children: [{
            id: '1',
            name: 'Action',
            children: [{
                id: '1.1',
                name: 'InputData',
                children: []
            }, {
                id: '1.2',
                name: 'Listen',
                children: []
            }, {
                id: '1.3',
                name: 'Look',
                children: []
            }, {
                id: '1.4',
                name: 'Read',
                children: []
            }, {
                id: '1.5',
                name: 'Utter',
                children: []
            }, {
                id: '1.6',
                name: 'Visualization',
                children: []
            }]
        }, {
            id: '2',
            name: 'Activity',
            children: [{
                id: '2.1',
                name: 'Analyse',
                children: []
            }, {
                id: '2.2',
                name: 'Design',
                children: []
            }, {
                id: '2.3',
                name: 'Evaluate',
                children: []
            }, {
                id: '2.4',
                name: 'Implementation',
                children: []
            }, {
                id: '2.5',
                name: 'Modeling',
                children: []
            }, {
                id: '2.6',
                name: 'Test',
                children: []
            }]
        }, {
            id: '3',
            name: 'Community',
            children: [{
                id: '3.1',
                name: 'SocialNetwork',
                children: []
            }, {
                id: '3.2',
                name: 'VirtualCommunities',
                children: []
            }]
        }, {
            id: '4',
            name: 'Computer',
            children: [{
                id: '4.1',
                name: 'Hardware',
                children: []
            }, {
                id: '4.2',
                name: 'Interface',
                children: []
            }, {
                id: '4.3',
                name: 'Software',
                children: [{
                    id: '4.3.1',
                    name: 'ApplicationSoftware',
                    children: []
                }, {
                    id: '4.3.2',
                    name: 'Groupware',
                    children: []
                }, {
                    id: '4.3.3',
                    name: 'OperatingSystem',
                    children: []
                }]
            }]
        }, {
            id: '5',
            name: 'Concept',
            children: [{
                id: '5.1',
                name: 'ActivityTheoryConcept',
                children: []
            }, {
                id: '5.2',
                name: 'CHIConcept',
                children: [{
                    id: '5.2.1',
                    name: 'CHILaw',
                    children: []
                }, {
                    id: '5.2.2',
                    name: 'CHIModel',
                    children: [{
                        id: '5.2.2.1',
                        name: 'UserModel',
                        children: []
                    }, {
                        id: '5.2.2.2',
                        name: 'DialogModel',
                        children: []
                    }, {
                        id: '5.2.2.3',
                        name: 'InterfaceModel',
                        children: []
                    }, {
                        id: '5.2.2.4',
                        name: 'ModelViewController',
                        children: []
                    }, {
                        id: '5.2.2.5',
                        name: 'TaskModel',
                        children: []
                    }]
                }, {
                    id: '5.2.3',
                    name: 'CognitiveErgonomicsConcept',
                    children: [{
                        id: '5.2.3.1',
                        name: 'FlowState',
                        children: []
                    }, {
                        id: '5.2.3.2',
                        name: 'Principles',
                        children: []
                    }]
                }, {
                    id: '5.2.4',
                    name: 'Interface',
                    children: [{
                        id: '5.2.4.1',
                        name: 'CollaborativeInterface',
                        children: []
                    }, {
                        id: '5.2.4.2',
                        name: 'DirectManipulationInterface',
                        children: []
                    }, {
                        id: '5.2.4.3',
                        name: 'InteligentInterfaces',
                        children: []
                    }, {
                        id: '5.2.4.4',
                        name: 'Virtual-reality',
                        children: []
                    }]
                }, {
                    id: '5.2.5',
                    name: 'Usability',
                    children: []
                }]
            }, {
                id: '5.3',
                name: 'CommunicationTtheoryConcept',
                children: []
            }, {
                id: '5.4',
                name: 'DialogismConcept',
                children: [{
                    id: '5.4.1',
                    name: 'Dialog',
                    children: []
                }, {
                    id: '5.4.2',
                    name: 'Heteroglosy',
                    children: []
                }, {
                    id: '5.4.3',
                    name: 'Interanimation',
                    children: []
                }, {
                    id: '5.4.4',
                    name: 'Polyphony',
                    children: []
                }, {
                    id: '5.4.5',
                    name: 'SpeechGenre',
                    children: []
                }, {
                    id: '5.4.6',
                    name: 'Utterance',
                    children: []
                }, {
                    id: '5.4.7',
                    name: 'Ventriloquation',
                    children: []
                }, {
                    id: '5.4.8',
                    name: 'Voice',
                    children: []
                }]
            }, {
                id: '5.5',
                name: 'EthnologyConcept',
                children: []
            }, {
                id: '5.6',
                name: 'EthnometodologyConcept',
                children: [{
                    id: '5.6.1',
                    name: 'ConversationAnalysis',
                    children: []
                }]
            }, {
                id: '5.7',
                name: 'LinguisticsConcept',
                children: []
            }, {
                id: '5.8',
                name: 'SemioticConcept',
                children: [{
                    id: '5.8.1',
                    name: 'Sign',
                    children: []
                }, {
                    id: '5.8.2',
                    name: 'Interpreter',
                    children: []
                }]
            }]
        }, {
            id: '6',
            name: 'Document',
            children: [{
                id: '6.1',
                name: 'Header',
                children: []
            }, {
                id: '6.2',
                name: 'Highlight',
                children: []
            }, {
                id: '6.3',
                name: 'Hypermedia',
                children: [{
                    id: '6.3.1',
                    name: 'Hypertext',
                    children: []
                }, {
                    id: '6.3.2',
                    name: 'Web',
                    children: []
                }]
            }, {
                id: '6.4',
                name: 'Image',
                children: []
            }, {
                id: '6.5',
                name: 'Link',
                children: []
            }, {
                id: '6.6',
                name: 'Paragraph',
                children: []
            }, {
                id: '6.7',
                name: 'Sound',
                children: []
            }, {
                id: '6.8',
                name: 'Text',
                children: []
            }, {
                id: '6.9',
                name: 'Video',
                children: []
            }, {
                id: '6.10',
                name: 'Anchor',
                children: []
            }]
        }, {
            id: '7',
            name: 'Feature',
            children: [{
                id: '7.1',
                name: 'Property',
                children: []
            }, {
                id: '7.2',
                name: 'Advantage',
                children: []
            }, {
                id: '7.3',
                name: 'Disadvantage',
                children: []
            }]
        }, {
            id: '8',
            name: 'Folksonomy',
            children: []
        }, {
            id: '9',
            name: 'Human',
            children: [{
                id: '9.1',
                name: 'HumanPhysiologicalFeature',
                children: []
            }, {
                id: '9.2',
                name: 'HumanPsychologicalFeature',
                children: []
            }, {
                id: '9.3',
                name: 'User',
                children: []
            }]
        }, {
            id: '10',
            name: 'Language',
            children: [{
                id: '10.1',
                name: 'NaturalLanguage',
                children: []
            }, {
                id: '10.2',
                name: 'ArtificialLanguage',
                children: [{
                    id: '10.2.1',
                    name: 'MarkupLanguage',
                    children: [{
                        id: '10.2.1.1',
                        name: 'SGML',
                        children: []
                    }, {
                        id: '10.2.1.2',
                        name: 'SVG',
                        children: []
                    }, {
                        id: '10.2.1.3',
                        name: 'Troff',
                        children: []
                    }, {
                        id: '10.2.1.4',
                        name: 'WebML',
                        children: []
                    }, {
                        id: '10.2.1.5',
                        name: 'XML',
                        children: []
                    }, {
                        id: '10.2.1.6',
                        name: 'HTML',
                        children: []
                    }, {
                        id: '10.2.1.7',
                        name: 'LaTeX',
                        children: []
                    }]
                }, {
                    id: '10.2.2',
                    name: 'Process',
                    children: [{
                        id: '10.2.2.1',
                        name: 'Understanding',
                        children: []
                    }, {
                        id: '10.2.2.2',
                        name: 'Collaboration',
                        children: []
                    }, {
                        id: '10.2.2.3',
                        name: 'Cooperation',
                        children: []
                    }, {
                        id: '10.2.2.4',
                        name: 'Immersion',
                        children: []
                    }, {
                        id: '10.2.2.5',
                        name: 'Navigation',
                        children: []
                    }]
                }, {
                    id: '10.2.3',
                    name: 'ProgrammingLanguage',
                    children: [{
                        id: '10.2.3.1',
                        name: 'C',
                        children: []
                    }, {
                        id: '10.2.3.2',
                        name: 'C++',
                        children: []
                    }, {
                        id: '10.2.3.3',
                        name: 'Cofeescript',
                        children: []
                    }, {
                        id: '10.2.3.4',
                        name: 'Csharp',
                        children: []
                    }, {
                        id: '10.2.3.5',
                        name: 'Earlang',
                        children: []
                    }, {
                        id: '10.2.3.6',
                        name: 'Haskell',
                        children: []
                    }, {
                        id: '10.2.3.7',
                        name: 'Java',
                        children: []
                    }, {
                        id: '10.2.3.8',
                        name: 'Javascript',
                        children: []
                    }, {
                        id: '10.2.3.9',
                        name: 'Lisp',
                        children: []
                    }, {
                        id: '10.2.3.10',
                        name: 'Perl',
                        children: []
                    }, {
                        id: '10.2.3.11',
                        name: 'Prolog',
                        children: []
                    }, {
                        id: '10.2.3.12',
                        name: 'Python',
                        children: []
                    }, {
                        id: '10.2.3.13',
                        name: 'Ruby',
                        children: []
                    }, {
                        id: '10.2.3.14',
                        name: 'Scala',
                        children: []
                    }, {
                        id: '10.2.3.15',
                        name: 'Scheme',
                        children: []
                    }]
                }]
            }]
        }, {
            id: '11',
            name: 'Ontology',
            children: []
        }, {
            id: '12',
            name: 'Problem',
            children: []
        }, {
            id: '13',
            name: 'TagCloud',
            children: []
        }]
    };
});
