export var AboutItemsData = [
    {
        title: 'ReaderBench - an Open-Source Framework',
        description: 'ReaderBench is an automated software framework designed to support both students and tutors by making use of text mining techniques, advanced natural language processing, and social network analysis tools. ReaderBench is centered on comprehension prediction and assessment based on a cohesion-based.representation of the discourse applied on different sources (e.g., textual materials, behavior tracks, metacognitive explanations, Computer Supported Collaborative Learning - CSCL - conversations). Therefore, ReaderBench can act as a Personal Learning Environment (PLE) which incorporates both individual and collaborative assessments. Besides the a priori evaluation of textual materials\' complexity presented to learners, our system supports the identification of reading strategies evident within the learners\' self-explanations or summaries. Moreover, ReaderBench integrates a dedicated cohesion-based module to assess participation and collaboration in CSCL conversations.'
    },
    {
        title: "ReaderBench's Purpose",
        description: 'Designed as support for both tutors and students, our implemented system, ReaderBench, can be best described as an educational learning helper tool to enhance the quality of the learning process. ReaderBench is a fully functional framework that enhances learning using various techniques such as textual complexity assessment, voice modeling for CSCL discourse analysis, topics modeling using Latent Semantic Analysis and Latent Dirichlet Allocation, and virtual communities of practice analysis.Our system was developed building upon indices provided in renowned systems such as E-rater, iSTART, and Coh-Metrix. However, ReaderBench provides an integration of these systems. ReaderBench includes multi-lingual comprehensioncentered analyses focused on semantics, cohesion and dialogism. For tutors, ReaderBench provides (a) the evaluation of reading material\'s textual complexity, (b) the measurement of social collaboration within a group endeavors, and (c) the evaluation of learners\' summaries and self-explanations. For learners, ReaderBench provides (a) the improvement of learning capabilities through the use of reading strategies, and (b) the evaluation of students\' comprehension levels and performance with respect to other students. ReaderBench maps directly onto classroom education, combining individual learning methods with Computer Supported Collaborative Learning (CSCL) techniques.'
    }
];